services:
  - type: web
    name: coachjv-crypto
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_admin
    startCommand: gunicorn cryptoplatform.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com,coachjv-crypto.onrender.com
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_NOnHIzUEV1T5@ep-curly-king-apo21r98-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: CLOUDINARY_URL
        value: cloudinary://688661857792261:LGe4IdMIbnhTE_4FYFgkwanf5Qo@dgo9rlph6
      - key: CLOUDINARY_CLOUD_NAME
        value: dgo9rlph6
      - key: CLOUDINARY_API_KEY
        value: "688661857792261"
      - key: CLOUDINARY_API_SECRET
        value: LGe4IdMIbnhTE_4FYFgkwanf5Qo
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: kingsleyotisi46@icloud.com
      - key: ADMIN_PASSWORD
        value: CryptoAdmin2026!
