# Generated by Django 6.0.5 on 2026-05-06 14:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Bitcoin Conservative Pool', max_length=100)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('conservative', 'Conservative - Low Risk'), ('balanced', 'Balanced - Medium Risk'), ('aggressive', 'Aggressive - High Risk')], max_length=20)),
                ('currency', models.CharField(default='USDT', help_text='Base currency for pool', max_length=10)),
                ('total_value', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Current total pool value', max_digits=20)),
                ('total_invested', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('available_capital', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Capital available for trading', max_digits=20)),
                ('share_price', models.DecimalField(decimal_places=8, default=Decimal('100.00'), help_text='Current price per share', max_digits=20)),
                ('total_shares', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('min_investment', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('max_investment', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=10)),
                ('lock_period_days', models.IntegerField(default=30, help_text='Minimum days before withdrawal')),
                ('total_profit', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('total_loss', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Return on Investment %', max_digits=10)),
                ('management_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Annual management fee %', max_digits=5)),
                ('performance_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Performance fee on profits %', max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active - Accepting Investments'), ('closed', 'Closed - Not Accepting New Investors'), ('paused', 'Paused')], default='active', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investment Pool',
                'verbose_name_plural': 'Investment Pools',
                'ordering': ['-featured', '-total_value'],
            },
        ),
        migrations.CreateModel(
            name='PoolTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(help_text='e.g., BTC/USDT', max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Amount traded', max_digits=20)),
                ('profit_loss', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('profit_loss_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('partial', 'Partially Filled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_pool_trades', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.investmentpool')),
            ],
            options={
                'verbose_name': 'Pool Trade',
                'verbose_name_plural': 'Pool Trades',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('investment', 'Investment - Buy Shares'), ('withdrawal', 'Withdrawal - Sell Shares'), ('profit_distribution', 'Profit Distribution'), ('management_fee', 'Management Fee'), ('performance_fee', 'Performance Fee')], max_length=30)),
                ('shares', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('share_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Amount in pool currency', max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.investmentpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pool Transaction',
                'verbose_name_plural': 'Pool Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('share_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('roi_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_change', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_investors', models.IntegerField(default=0)),
                ('trades_count', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='core.investmentpool')),
            ],
            options={
                'verbose_name': 'Pool Performance Snapshot',
                'verbose_name_plural': 'Pool Performance Snapshots',
                'ordering': ['-date'],
                'unique_together': {('pool', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PoolShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_owned', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=8, help_text='Average purchase price per share', max_digits=20)),
                ('total_invested', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('total_profit_received', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('last_profit_date', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='core.investmentpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pool Share',
                'verbose_name_plural': 'Pool Shares',
                'ordering': ['-total_invested'],
                'unique_together': {('user', 'pool')},
            },
        ),
    ]
