# Generated by Django 4.2.30 on 2026-05-16 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_investmentpool_pooltrade_pooltransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email where OTP was sent', max_length=254)),
                ('token', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('login_2fa', 'Two-Factor Authentication Login'), ('withdrawal_confirm', 'Withdrawal Confirmation'), ('account_change', 'Account Settings Change')], max_length=30)),
                ('is_used', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.IntegerField(default=5)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (e.g., withdrawal ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Token',
                'verbose_name_plural': 'OTP Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_valid'], name='core_otptok_user_id_7495f8_idx'), models.Index(fields=['token', 'is_valid'], name='core_otptok_token_08b1d8_idx')],
            },
        ),
    ]
