# Generated by Django 6.0.5 on 2026-05-18 09:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otptoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_level', models.CharField(choices=[('free', 'Free'), ('warrior', 'Warrior'), ('ascension', 'Ascension Plus'), ('vip', 'VIP')], max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField()),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_investment_pools', models.IntegerField(default=1, help_text='Max pools can invest in')),
                ('max_withdrawal_per_day', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=20)),
                ('priority_support', models.BooleanField(default=False)),
                ('access_courses', models.BooleanField(default=False)),
                ('access_live_events', models.BooleanField(default=False)),
                ('access_private_coaching', models.BooleanField(default=False)),
                ('access_community_forum', models.BooleanField(default=False)),
                ('access_resource_library', models.BooleanField(default=False)),
                ('access_portfolio_tracker', models.BooleanField(default=True)),
                ('access_wealth_tools', models.BooleanField(default=False)),
                ('access_insurance_services', models.BooleanField(default=False)),
                ('access_crypto_ira', models.BooleanField(default=False)),
                ('trading_fee_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Trading fee discount %', max_digits=5)),
                ('withdrawal_fee_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Withdrawal fee discount %', max_digits=5)),
                ('referral_bonus_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Referral bonus multiplier', max_digits=5)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('badge_color', models.CharField(default='#6c757d', help_text='Badge color hex code', max_length=20)),
                ('icon', models.CharField(default='fa-user', help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Tier',
                'verbose_name_plural': 'Membership Tiers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending Payment')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_method', models.CharField(blank=True, help_text='e.g., Stripe, PayPal, Crypto', max_length=50)),
                ('payment_id', models.CharField(blank=True, help_text='External payment system ID', max_length=100)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('billing_count', models.IntegerField(default=0, help_text='Number of successful billings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.membershiptier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Membership',
                'verbose_name_plural': 'User Memberships',
            },
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('billing_cycle', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_id', models.CharField(blank=True, help_text='External payment system ID', max_length=100)),
                ('transaction_id', models.CharField(blank=True, help_text='Internal transaction reference', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.usermembership')),
            ],
            options={
                'verbose_name': 'Membership Payment',
                'verbose_name_plural': 'Membership Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
